"""Shared rendering helpers for the C4 generator.

The active renderer is ``puml.py`` (C4-PlantUML, rendered to SVG by Kroki — see
``cli.py``). This module holds the small, renderer-agnostic helpers it relies on:
id/label sanitization, concise taglines, node-owner resolution, the context-group
alias, the shared async/sync colours, and the generated-file banner.

(There is no Mermaid renderer any more; it was replaced by C4-PlantUML.)
"""

from __future__ import annotations

import textwrap

from .schema import Model

# Async edges are amber; sync are blue. Used by the page legend (pages.py) and
# mirrored by the PlantUML async relationship tag (puml.py).
ASYNC_COLOR = "#e8a33d"
SYNC_COLOR = "#4c9be8"

BANNER = (
    "<!-- GENERATED by architecture_maps/c4gen — do not hand-edit.\n"
    "     Edit architecture_maps/models/{model}.yaml, then from architecture_maps/ run\n"
    "     `uv run --group c4gen python -m c4gen render {model}` with a local Kroki\n"
    "     running (see architecture_maps/README.md). -->\n"
)


def alias(node_id: str) -> str:
    """Sanitize a node id into an identifier-safe diagram alias."""
    return node_id.replace("-", "_").replace(".", "_")


def q(text: str) -> str:
    """Quote a string for a C4 macro argument.

    Labels are plain text wrapped in double quotes; the only thing that breaks
    the parser is an embedded double quote, so swap those for single quotes and
    collapse whitespace/newlines.
    """
    return '"' + " ".join((text or "").replace('"', "'").split()) + '"'


def _short(text: str, width: int = 90) -> str:
    text = " ".join((text or "").split())
    return textwrap.shorten(text, width=width, placeholder="…") if text else ""


def _tagline(text: str, limit: int = 46) -> str:
    """A concise in-shape description (C4 rule: keep under ~50 chars).

    Prefer cutting at a natural clause boundary; fall back to a word-boundary
    truncation. Full prose stays in the page tables.
    """
    text = " ".join((text or "").split())
    if not text:
        return ""
    for sep in (";", " — ", " (", ". "):
        i = text.find(sep)
        if 0 < i <= limit:
            return text[:i]
    if len(text) <= limit:
        return text
    return text[:limit].rsplit(" ", 1)[0] + "…"


def _group_alias(label: str) -> str:
    """Alias for a System Context group black box (collapsed external systems)."""
    slug = "".join(c if c.isalnum() else "_" for c in label.lower())
    return "grp_" + slug.strip("_")


def _owner_id(model: Model, node_id: str) -> str:
    """Resolve a node id to the id used at system level (its system, or itself if actor)."""
    if any(a.id == node_id for a in model.actors):
        return node_id
    system = model.system_of(node_id)
    return system.id if system else node_id
