on: [push]

jobs:
  nikola_build:
    runs-on: ubuntu-latest
    name: 'Deploy Nikola to GitHub Pages'
    steps:
    - name: Fix git safe.directory in container
      run: mkdir -p /home/runner/work/_temp/_github_home && printf "[safe]\n\tdirectory = /github/workspace" > /home/runner/work/_temp/_github_home/.gitconfig
    - name: Check out
      uses: actions/checkout@v4
      with:
        set-safe-directory: '*'
    - name: Build and Deploy Nikola
      uses: getnikola/nikola-action@v4
      with:
        dry_run: false
